### ISSUE TITLE
New Theme Repo

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt-themes#1]
Splitted out the theme, icons and graphics part from lxqt-common - please let me know your opinion and possible needed changes

**Comment by tsujan** [comment]
It's great. (Sorry for the late response; you've been very fast and I've been very busy.)

**Comment by palinek** [comment]
Yes, the new repo seems good.

**Comment by luis-pereira** [comment]
It's good. Didn't find any issue.

**Comment by agaida** [comment]
hmm - maybe it would be wise to write a little note into lxde-list about the latest changes. I think i will do this right now.

**Comment by m4sk1n** [comment]
What about making lxqt-themes-extra repo containing more (unofficial) themes on LGPL-compatible licenses?

**Comment by agaida** [comment]
why not?
