### ISSUE TITLE
Clearlooks has no visible #ColorPicker divider

### ISSUE THREAD

**Issue by isf63** [lxqt/lxqt-themes#102]
I noticed there is no visible QFrame divider from the Color Picker widget, but of the 12 themes, only in Clearlooks.

Setting `LXQtPanel #BackgroundWidget { background-color: green; }` results in:

![image](https://github.com/lxqt/lxqt-themes/assets/121320947/98399553-d557-4a9d-86e4-8bd4608f6525)

However, setting `#ColorPicker QFrame { background: red; }` shows that there is a bounding box for it still:

![image2](https://github.com/lxqt/lxqt-themes/assets/121320947/9eeb7026-acf0-4c87-970d-6eb353bc1d49)

**Comment by isf63** [comment]
Not sure how I missed this at first look: 
https://github.com/lxqt/lxqt-themes/blob/f33eee46eb69a87859a373cf03ed7e6afc38d6a2/themes/Clearlooks/lxqt-panel.qss#L13
affects `ColorPickerPlugin → ColorPickerWidget → QFrame`.

**Comment by stefonarch** [comment]
It's also good visible in Leech:
![screen_area_mar_19:12:02_](https://github.com/lxqt/lxqt-themes/assets/10681413/9d38302e-0715-41c3-8f28-34d5aa32179f)

**Comment by isf63** [comment]
@stefonarch, it's the same as Clearlooks: https://github.com/lxqt/lxqt-themes/blob/f33eee46eb69a87859a373cf03ed7e6afc38d6a2/themes/Leech/lxqt-panel.qss#L13

In both cases `border: 0px;` hides the frame.
