### ISSUE TITLE
the system theme do not have main menu icon set

### ISSUE THREAD

**Issue by sztsian** [lxqt/lxqt-themes#15]
##### Expected Behavior

Themes should have an icon for main menu.

##### Current Behavior

However, there is no icon for main menu if user choose the system theme

##### Possible Solution

I checked the theme file and find it is actually left empty
https://github.com/lxqt/lxqt-themes/blob/master/themes/system/lxqt-panel.qss#L62
So I wonder if this is intended or not?
If this is intended, does anyone remember the basic idea for keep this empty?

##### Steps to Reproduce (for bugs)

1. Preferences/Appearance
2. Select LXQt Theme
3. Select "System" and apply
4. Check the main menu

![System Theme LXQt](https://user-images.githubusercontent.com/5670072/72777876-14aba700-3c52-11ea-8b3e-1a087b70b9b4.png)
##### Context

This is a follow-up to the Fedora bug
https://bugzilla.redhat.com/show_bug.cgi?id=1793137
I'd like to know why before fixing it in Fedora.

##### System Information

* Distribution & Version:  Fedora
* Kernel: 
* Qt Version: 
* lxqt-build-tools Version:
* libqtxdg Version:
* Package version: 
qt5-qtbase-5.13.2-1.fc31.x86_64
lxqt-themes-0.14.0-2.fc31.noarch
libqtxdg-3.3.1-7.fc31.x86_64
The whole LXQt stack in Fedora 31 is built against lxqt-build-tools-0.6.0-1

**Comment by palinek** [comment]
Based on commit history it was intentional -> https://github.com/lxqt/lxqt-themes/commit/e4d03c1d130841d57e484fc56241b53ee0c4385d#diff-33da7ceb1a0992731729961ac3b97e54
I really don't remember the reasoning. Looking at it now, IMO we could use `graphics/helix.svg` there.

**Comment by tsujan** [comment]
Or we can use the theme icon `start-here-lxqt` with the system theme.

**Comment by M6894** [comment]
@tsujan please consider adding the `graphics/helix.svg` to `#MainMenu` of the system theme. 
Thank you in advance.
