### ISSUE TITLE
[Feature Request] LXQt needs saner defaults and more familiar themes. I may be able to help?

### ISSUE THREAD

**Issue by AzumaHazuki** [lxqt/lxqt-themes#17]
I want to like LXQt more, but getting a consistent look and feel is difficult to say the least. The project does not leave a favorable or unified impression on its first presentation.

On pling.com I've been reproducing some more familiar Linux (and Windows-ish...) themes for LXQt's panel, and already have panel stylesheets for Oxygen, Windows XP, Windows 9x/2000, and Clearlooks. As of now they are _only_ panel themes (in other words I've not themed the Runner dropdown, etc. yet), but I believe the Clearlooks theme shows promise and might even be a good default.

What helps the case is that there already exist Clearlooks GTK2 and 3 themes (Clearlooks-Phenix) and an Openbox theme, and Qt's Fusion theme is close enough to Clearlooks to be an acceptable default, though it would be even better if LXQt came with QtCurve and a Clearlooks QtCurve theme set by default as well.

Link here: https://www.pling.com/p/1388153

![LXQtClearlooks](https://user-images.githubusercontent.com/67122280/85065265-da9bee00-b17a-11ea-8de0-75fc7a35229b.jpg)

My suggestion consists of these ideas:

- Default LXQt's themes to 
-- Clearlooks (Openbox)
-- Clearlooks-Phenix (GTK2 _and_ GTK3)
-- Clearlooks-LXQt (my theme from above)
-- either Fusion for the Qt theme, or QtCurve with an appropriate theme like https://www.pling.com/p/1005221
-- Noto fonts installed and set to size 9 or 10 by default
-- Elementary KDE Blue icon set from https://www.pling.com/p/1284551 by default 

I don't know if the LXQt team is open to the idea of adding any of these to the default distribution, as it could entail making QtCurve a dependency if Fusion isn't left default (and either pulling in a lot of KDE if a given distro's QtCurve package is built with KDE support or necessitating a "QtCurve-NoKDE" or "QtCurve-Qt5-only" package if a given distro doesn't have these)...

Please let me know what you all think, and if I should finish the Clearlooks theme to cover the Runner dropdown and other parts besides the panel.

**Comment by tsujan** [comment]
Please don't start discussions that are only based on tastes. Tastes differ and so, such discussions will be futile.

Fusion is the default Qt widget style and so, the default LXQt's widget style. LXQt users are free to use any widget style -- Fusion, Breeze, Kvantum, QtCurve,....

Neither Openbox nor GTK is a part of LXQt. So, no, we don't add Openbox/GTK themes to LXQt. But distros are free to do so in any way they like. They may also want to add KWin decorations, etc.

The same is true for icon sets and fonts.

However, you could make a PR for your *LXQt theme(s)* (for panel, runner,...) to be added to the current collection. I guess you have one with the name "Clearlooks".

So, yes, please complete your LXQt theme and make a PR. It'll be very appreciated.

**Comment by tsujan** [comment]
Sorry, I closed this by mistake. You could add comments and they'll be read.

**Comment by AzumaHazuki** [comment]
It's been a while (life has been insane and is getting insane-r) but I think I'm done with the Clearlooks theme: https://www.pling.com/p/1388153/

It's market 0.9b but may become the final release if nothing more needs to be done with it. Does this look worthy of being included in LXQt's themes collection?

**Comment by tsujan** [comment]
> Does this look worthy of being included in LXQt's themes collection?

Why not? The screenshot looks good. Please make a PR!

**Comment by AzumaHazuki** [comment]
I'm sorry, but I can't seem to figure out how to do this. I've created my own repository but don't know how to make a pull request from there to here (or even if that's possible and/or correct). Am trying to find a guide that explains this in simple language.

**Comment by tsujan** [comment]
GitHub has a comprehensive documentation. You could start with https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests and follow its links.

**Comment by antis81** [comment]
@AzumaHazuki Would you mind to fork & clone the project to open a pull request? You don't need to compile LXQt, but you will need a local copy to create a theme.

**Comment by tsujan** [comment]
He has already done it and his themes are in LXQt 0.16. I forgot to close this page.
