### ISSUE TITLE
`waves-purple-logo.png` is too big

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-themes#62]
Converting it to jpg with GIMP didn't cause any loss in its visible quality, while it reduced its size from 15.9 MiB to 387.1 KiB. The converted image is attached as zipped.

[waves-purple-logo.jpg.zip](https://github.com/lxqt/lxqt-themes/files/8426130/waves-purple-logo.jpg.zip)

**Comment by stefonarch** [comment]
Wow, didn't notice the filesize, came out of gimp export.

**Comment by isf63** [comment]
Might want to convert the remaining photo PNGs to JPG, cloning lxqt-themes takes a while on slow connections. The repo is 50MiB and `/usr/share/lxqt/wallpapers/*.png` is 26MiB.

**Comment by tsujan** [comment]
I also think that a correct conversion from PNG to JPG is a good idea (I wanted to propose it but forgot). GIMP can do it efficiently. Sometimes the sizes are decreased considerably, without any loss to the visual quality.
