### ISSUE TITLE
Setting Application style to QStyleSheet?

### ISSUE THREAD

**Issue by sammonius** [lxqt/lxqt-themes#72]
I can make this feature myself if it would be more convenient, but my question is weather this would be wanted or not? I made a similar suggestion on the kde-devel[opment] mailing list and I found that qstylesheets seem to have a bad reputation for some reason [(copy of conversation)](https://pastebin.com/raw/J2yV6pf1). Would the LXQt community/developers be more open to a feature like this?

The common misconception is that QStyleSheets don't have as much customization power as a QStylePlugin in C++ (which is what Breeze, Oxygen, Fusion, etc... are made using), but this isn't true. For proof, see [this repo containing a copy of Breeze theme as a qstylesheet](https://github.com/Alexhuszagh/BreezeStyleSheets) (where the stylesheet file is located in src/dist/qrc/light/stylesheet.qss)

**Comment by tsujan** [comment]
`QStyleSheetStyle` is derived from `QWindowsStyle` and, like any style plugin, is written in C++. You may make a style plugin based on it. If you do so, LXQt will find it, like it finds other style plugins.

However, none of this is directly related to LXQt because LXQt is agnostic toward all style plugins.

**Comment by tsujan** [comment]
BTW, Milian Wolff's reply in [your link](https://pastebin.com/raw/J2yV6pf1) is similar to mine: "Adding this feature won't make the C++ styles disappear...".

The other reply about the shortcomings of Qt stylesheets reflects the replier's opinion. Although I completely agree with him, it isn't related to what I said above.
