### ISSUE TITLE
Palette colors for same elements in darkthemes in qtlinguist and other applications

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-themes#85]
Those colors for html and placeholder are always the same, from the default palette:

![screen-23 lug_20:15](https://user-images.githubusercontent.com/10681413/180617874-32da7f15-2e83-4e38-b300-914fce50dc89.jpg)
![screen-23 lug_20:16](https://user-images.githubusercontent.com/10681413/180617875-1c3be3f7-8460-4165-904f-cbc1e1eda039.jpg)

##### Expected Behavior

I' like to see well the text
##### Current Behavior

I don,t, higligting all is needed to distinct well.
##### Possible Solution

Set them in all dark themes to something brighter.

https://doc.qt.io/qt-5/qpalette.html

##### Context

It made me make mistakes.
##### System Information

* Distribution & Version: latest git

**Comment by tsujan** [comment]
They're link colors. If they are the same, then the app uses hard-coded colors, which is a bad practice and should be fixed in the app..

**Comment by tsujan** [comment]
BTW, don't be surprised if an app like Linguist or Qt Creator has GUI problems. One may expect that, at least, apps that belong to Qt shouldn't have GUI issues, but that's far from the truth.

LXQt apps are mostly OK, if not all.

**Comment by tsujan** [comment]
Closing?

**Comment by tsujan** [comment]
Also, see https://bugreports.qt.io/browse/QTBUG-54203 (see its date and priority).

As far as I've seen, many devs have "style blindness". GNOME devs found a cure that fits in their tradition: https://stopthemingmy.app/

The real solution is: either leave your app to the active style or respect basic rules of styling.
