### ISSUE TITLE
EXIF data in some of stefonarch's photos contains conflicting licensing information

### ISSUE THREAD

**Issue by ArrayBolt3** [lxqt/lxqt-themes#91]
As part of packaging software for Debian, I am going through the source code files of LXQt and documenting their copyright and licensing info. During this process, I discovered a somewhat hilarious and initially alarming problem.

In order to extract licensing information from the numerous PNG and other files in lxqt-themes, I used exiftool to extract EXIF information from the pictures and then grepped through them for lines containing the words "license" and "copyright".

In so doing, I discovered a number of pictures in lxqt-themes/wallpapers who's EXIF data indicated that they were licensed under CC-BY-NC-SA-2.0 or CC-BY-NC-SA-1.0, namely beam.png, fog.jpg, this-is-not-windows.jpg, and Valendas.jpg. Upon further investigation, it appears that these photos are copyrighted by stefonarch. According to lxqt-themes/wallpapers/License, these photos are licensed under CC-BY-SA 3.0. (Valendas.jpg is not specifically mentioned in that file, however the License file appears to specify the license of the entire folder, and the EXIF data indicates that the copyright owner of Valendas.jpg is the same as the copyright owner of the other three files, which are identified as belonging to stefonarch.)

This is slightly problematic, as files that are licensed under CC-BY-NC-SA are not able to be included in Debian's Main archive, but files licensed under CC-BY-SA 3.0 are allowed. It appears that the photos in lxqt-themes are also on stefonarch's blog, and that for the blog, they are licensed under CC-BY-NC-SA 2.0, but for LXQt, they are licensed under CC-BY-SA 3.0.

If this is the case, it would be helpful if the EXIF data for the files in question could be modified to specify the same license as is specified in the License file. Or if the files *are* under CC-BY-NC-SA, it would be helpful if the License file indicated this.

Pinging @stefonarch as the photos in question are under his copyright, to the best of my knowledge. Thank you!

(Edit: Only the four files mentioned appear to have problems, the other ones appear to be OK.)

**Comment by ArrayBolt3** [comment]
@stefonarch I'm able to modify "Copyright Notice" with `exiftool '-CopyrightNotice=text here'`. Does that work?

**Comment by stefonarch** [comment]
It does :) 
I tried `Copyright\ Notice=` no error  and no result.
Thanks!
